name: Run MTG tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run API tests
      run: npm run test:api

    - name: Upload API Allure Report as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with: 
        name: allure-report-api
        path: allure-report

  mtg-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run WDIO tests
      run: npm run test:mobile

    - name: Upload UI Allure Report as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with: 
        name: allure-report-ui
        path: allure-report

  deploy:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [api-tests, mtg-tests]

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download API report as artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-report-api
        path: merged-results/api

    - name: Download UI report as artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-report-ui
        path: merged-results/ui

    - name: Merge results
      run: |
        mkdir -p allure-results
        cp -r merged-results/api/* allure-results || true
        cp -r merged-results/ui/* allure-results || true

    - name: Generate Allure report
      if: ${{ always() }} 
      run: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: out

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4